blueprint:
  name: Turn On/Off a Light/Switch at a fixed time each days
  description: Turn on/off a light / switch at a fixed time each days.Exemple with Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days.
  domain: automation
  source_url: https://github.com/Agezeram-Fr/hass-switch-light-on-off-terra/blob/main/switch-light-on-off-terra.yaml
  author: Agezeram
  input:
    switch_light:
        name: Switch / Light
        selector:
            entity:
                domain:
                  - switch
                  - light
    
    on_time:
      name: ON Time
      description: Set ON time.
      default: 00:00:00
      selector:
       time:
    off_time:
      name: OFF Time
      description: Set OFF time.
      default: 00:00:00
      selector:
        time:
        
    weekday_options:
      name: Weekdays
      description: Select the days of the week you would like the automation to run.
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          mode: list
          options:
            - label: Monday
              value: "mon"
            - label: Tuesday
              value: "tue"
            - label: Wednesday
              value: "wed"
            - label: Thursday
              value: "thu"
            - label: Friday
              value: "fri"
            - label: Saturday
              value: "sat"
            - label: Sunday
              value: "sun"

# Automation schema
#alias: TERRA120 ON/OFF (14h30->02h30)(12H light)
description: "BASE-OK_01"
#mode: restart

variables:
  on_time: !input on_time
  off_time: !input off_time
  switch_light: !input switch_light

trigger:
  - platform: time
    #at: "ontime"
    at: !input on_time
    #id: Switch-Light-ON
    id: "ontime"
  - platform: time
    #at: "offtime"
    at: !input off_time
    #id: Switch-Light-OFF
    id: "offtime"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            #id: Switch-Light-ON
            id: "ontime"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: !input switch_light
      - conditions:
          - condition: trigger
            #id: Switch-Light-OFF
            id: "offtime"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: !input switch_light
mode: single
