blueprint:
  name: Switch / Light ON/OFF
  description: Turn on/off a light / switch at a fixed time each days.
                 Exemple with Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days.
  domain: automation
  source_url: 
  author: Agezeram

alias: TERRA120 ON/OFF (14h30->02h30)(12H light)
description: "Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days"
trigger:
  - platform: time
    at: "14:30:00"
    id: Switch-Light-ON
  - platform: time
    at: "02:30:00"
    id: Switch-Light-OFF
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Switch-Light-ON
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.terra120
      - conditions:
          - condition: trigger
            id: Switch-Light-OFF
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.terra120
mode: single
