blueprint:
  name: Turn On/Off a Light/Switch at a fixed time each days
  description: |
    Turn On/Off Switch/Light at a fixed time each days.
    
  domain: automation
  source_url: https://github.com/Agezeram-Fr/hass-switch-light-on-off-terra/blob/main/switch-light-on-off-terra.yaml
  author: Agezeram
  input:
    switch_light_entity:
        name: Switch / Light Entity
        selector:
            entity:
                domain:
                  - switch
                  - light
    
    sl_on:
      name: ON Time
      description: Set ON time.
      default: 00:00:00
      selector:
       time:
    sl_off:
      name: OFF Time
      description: Set OFF time.
      default: 00:00:00
      selector:
        time:
    weekday_options:
      name: Weekdays
      description: Select the days of the week you would like the automation to run. You must select "Enable the time options" above for the weekdays selections to work.
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          mode: list
          options:
            - label: Monday
              value: "mon"
            - label: Tuesday
              value: "tue"
            - label: Wednesday
              value: "wed"
            - label: Thursday
              value: "thu"
            - label: Friday
              value: "fri"
            - label: Saturday
              value: "sat"
            - label: Sunday
              value: "sun"

# Automation schema
alias: TERRA120 ON/OFF (14h30->02h30)(12H light)
description: "Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days"
#mode: restart

variables:
  sl_on: !input sl_on
  sl_off: !input sl_off
  switch_light_entity: !input switch_light_entity
  weekday_options: !input weekday_options
  
trigger:
  - platform: time
    #at: "ontime"
    at: !input sl_on
    #id: Switch-Light-ON
    id: "ontime"
  - platform: time
    #at: "offtime"
    at: !input sl_off
    #id: Switch-Light-OFF
    id: "offtime"
#condition: 
#  weekday: !input weekday_options
condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            #id: Switch-Light-ON
            id: "ontime"
            weekday: !input weekday_options
        sequence:
          - service: switch.turn_on
            data: {}
            target: !input switch_light_entity
      - conditions:
          - condition: trigger
            #id: Switch-Light-OFF
            id: "offtime"
            weekday: !input weekday_options
        sequence:
          - service: switch.turn_off
            data: {}
            target: !input switch_light_entity
mode: single
