blueprint:
  name: Turn On/Off a Light/Switch at a fixed time each days
  description: Turn on/off a light / switch at a fixed time each days.Exemple with Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days.
  domain: automation
  source_url: https://github.com/Agezeram-Fr/hass-switch-light-on-off-terra/blob/main/switch-light-on-off-terra.yaml
  author: Agezeram
  input:
    switch_light:
        name: Switch / Light
        selector:
            entity:
                domain:
                  - switch
                  - light
    
    sl_on:
      name: ON Time
      description: Set ON time.
      default: 00:00:00
      selector:
       time:
    sl_off:
      name: OFF Time
      description: Set OFF time.
      default: 00:00:00
      selector:
        time:


# Automation schema
alias: TERRA120 ON/OFF (14h30->02h30)(12H light)
description: "Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days"
#mode: restart

variables:
  sl_on: !input sl_on
  sl_off: !input sl_off
  switch_light: !input switch_light

trigger:
  - platform: time
    #at: "ontime"
    at: !input sl_on
    #id: Switch-Light-ON
    id: "ontime"
  - platform: time
    #at: "offtime"
    at: !input sl_off
    #id: Switch-Light-OFF
    id: "offtime"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            #id: Switch-Light-ON
            id: "ontime"
        sequence:
          - service: switch.turn_on
            data: {}
            target: !input switch_light
      - conditions:
          - condition: trigger
            #id: Switch-Light-OFF
            id: "offtime"
        sequence:
          - service: switch.turn_off
            data: {}
            target: !input switch_light
mode: single
