blueprint:
  name: Turn On/Off a Light/Switch at a fixed time from selected days.
  description: 👋 Turn On/Off a Light/Switch at a fixed time each days or selected days 👋
  ✏️ Installation <a href="https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgithub.com%2FAgezeram-Fr%2Fhass-switch-light-on-off-weekdays%2Fblob%2Fmain%2Fswitch-light-on-off-weekdays.yaml" target="_blank"><img src="https://my.home-assistant.io/badges/blueprint_import.svg" alt="Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled." /></a> ✏️
  ℹ️ Version 1.2 - 05/2023 ℹ️
  🔨    🔨
  domain: automation
  source_url: https://github.com/Agezeram-Fr/hass-switch-light-on-off-weekdays/blob/main/switch-light-on-off-weekdays.yaml
  author: Agezeram
  input:
    switch_light:
        name: Switch / Light
        selector:
            entity:
                domain:
                  - switch
                  - light
    
    sl_on:
      name: ON Time
      description: Set ON time.
      default: 00:00:00
      selector:
       time:
    sl_off:
      name: OFF Time
      description: Set OFF time.
      default: 00:00:00
      selector:
        time:
        
    weekdays_choice:
      name: Weekdays
      description: Select the days of the week you would like the automation to run.
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          mode: list
          options:
            - label: Monday
              value: "mon"
            - label: Tuesday
              value: "tue"
            - label: Wednesday
              value: "wed"
            - label: Thursday
              value: "thu"
            - label: Friday
              value: "fri"
            - label: Saturday
              value: "sat"
            - label: Sunday
              value: "sun"

# Automation schema
description: "BASE-OK_03_TIME_and_DAYS"

variables:
  sl_on: !input sl_on
  sl_off: !input sl_off
  switch_light: !input switch_light
  weekdays_choice: !input weekdays_choice

trigger:
  - platform: time
    at: !input sl_on
    id: "ontime"
  - platform: time
    at: !input sl_off
    id: "offtime"
condition:
- condition: time
  weekday: !input weekdays_choice
action:
  - choose:
      - conditions:
          - condition: trigger
            id: "ontime"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: !input switch_light
      - conditions:
          - condition: trigger
            id: "offtime"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: !input switch_light
mode: single
