blueprint:
  name: Turn On/Off a Light/Switch at a fixed time each days
  description: Turn on/off a light / switch at a fixed time each days.Exemple with Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days.
  domain: automation
  source_url: https://github.com/Agezeram-Fr/hass-switch-light-on-off-terra/blob/main/switch-light-on-off-terra.yaml
  author: Agezeram
  input:
    switch_light:
        name: Switch / Light
        selector:
            entity:
                #multiple: true
                domain:
                  - switch
                  - light
                  #- scene
                 #multiple: true
    
    slon:
      name: ON Time
      description: Set ON time.
      default: 00:00:00
      selector:
       time:
    sloff:
      name: OFF Time
      description: Set OFF time.
      default: 00:00:00
      selector:
        time:

#variables:
  #slon: !input slon
  #sloff: !include sloff
 # switch_light: !include switch_light

alias: TERRA120 ON/OFF (14h30->02h30)(12H light)
description: "Carnivorous plant's Terrarium swith on at 2:30pm, switch off 2:30am each days"

trigger:
  - platform: time
    #at: "ontime"
    at: !input slon
    #id: Switch-Light-ON
    id: "ontime"
  - platform: time
    #at: "offtime"
    at: !input sloff
    #id: Switch-Light-OFF
    id: "offtime"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            #id: Switch-Light-ON
            id: "ontime"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.terra120
      - conditions:
          - condition: trigger
            #id: Switch-Light-OFF
            id: "offtime"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.terra120
mode: single
